config/routes.rb
Rails.application.routes.draw do
  root 'domains#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'profile' => 'profile#edit'
  patch 'profile' => 'profile#update'

  resources :admins, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_EMAIL_LIKE do
        get 'edit'
        patch '', action: 'update', as: ''
        delete '', action: 'destroy'
      end
    end
  end

  resources :domains, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
        get 'edit', action: 'edit'
        get '', action: 'show', as: ''
        patch '', action: 'update'
        delete '', action: 'destroy'
      end
    end

    constraints domain_id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
      resources :aliases, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end

      resources :mailboxes, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end
    end
  end


end

app/controllers/aliases_controller.rb
class AliasesController < ApplicationController
  before_action :set_alias, only: [:edit, :update, :destroy]
  before_action :set_active_domain, only: [:index, :new, :create]

  def new
    @alias = Alias.new
  end

  def create
    @alias = Alias.new
    @alias.rel_domain = @domain
    # rel_domain must be set in advance
    @alias.assign_attributes(alias_params)

    if @alias.save
      redirect_to domain_aliases_path(@alias.domain), notice: 'Alias was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    unless @alias.address.nil?
      @alias.local_part = @alias.address.split("@").first
    end
  end

  def update
    if @alias.update(alias_params)
      path = if @alias.pure_alias?
               domain_aliases_path(@alias.domain)
             else
               domain_mailboxes_path(@alias.domain)
             end
      redirect_to path, notice: 'Alias was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @alias.destroy
    redirect_to domain_aliases_path(@alias.domain)
  end

  private

  def set_alias
    @alias = Alias.find(params[:id])
    set_active_domain
    raise "Invalid Paramters" if @alias.rel_domain != @domain
  end

  def alias_params
    params.require(:alias).permit(:local_part, :active, forward_addresses: [])
  end
end

app/helpers/aliases_helper.rb
module AliasesHelper
end

app/views/aliases/_form.html.erb
<%= form_for([@domain, @alias]) do |f| %>
  <div class="card-body">
  <% if @alias.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alias.errors.count, "error") %> prohibited this alias from being saved:</h2>

      <ul>
        <% @alias.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :local_part %><br>
    <% if controller.action_name == "edit" %>
      <%= f.hidden_field :local_part, size: 20 %>
      <%= @alias.address %>
    <% else %>
      <div class="input-group">
        <%= f.text_field :local_part, size: 20, class: "form-control" %>
        <div class="input-group-append">
          <div class="input-group-text">@<%= @domain.domain %></div>
        </div>
      </div>
    <% end %>

  </div>

  <div class="form-group" id="forward-address-group">
    <%= f.label :goto %>
    <% @alias.forward_addresses.each_with_index do |f, i| %>
      <div class="input-group mb-2 forward-address">
      <%= text_field_tag 'alias[forward_addresses][]', f, size: 50,
                         class: "form-control", readonly: i == 0 && @alias.mailbox? %>
        <div class="input-group-append <%= i == 0 ? "d-none" : "" %>">
          <button class="btn btn-outline-info delete-forward-address-button" type="button" <%= i == 0 ? "disabled" : "" %>>Delete</button>
        </div>
      </div>
    <% end %>
    <button class="btn btn-outline-info" id="add-forward-address-button" type="button">Add</button>
  </div>

  <% if @alias.pure_alias? %>
  <div class="form-group form-check">
    <%= f.check_box :active, class: "form-check-input" %>
    <%= f.label :active, class: "form-check-label" %>
  </div>
  <% end %>
  </div>

  <% cancel_path = @alias.pure_alias? ? domain_aliases_path(@domain) : domain_mailboxes_path(@domain)%>

  <div class="card-footer">
    <%= f.submit(class: "btn btn-primary") %>
    <%= link_to "Cancel", cancel_path, role: "button",
                class: "btn btn-secondary" %>
  </div>

<% end %>

app/views/aliases/edit.html.erb
<div class="card card-form">
  <h4 class="card-header">Edit alias</h4>
  <%= render 'form' %>
</div>

app/views/aliases/index.html.erb
<%= render "domains/info" %>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th class="text-center">#</th>
    <th>Alias</th>
    <th>To</th>
    <th class="text-center">Status</th>
    <th class="text-center">Edit</th>
    <th class="text-center">Delete</th>
    <th class="text-center">Modified</th>
  </tr>
  </thead>
  <tbody>
  <% @domain.pure_aliases.each_with_index do |a, i| %>
    <% tr_class = a.active? ? "" : "table-secondary" %>
    <tr class="<%= tr_class %>">
      <td><%= i+1 %></td>
      <td><%= a.address %></td>
      <td>
        <% a.gotos.each do |g| %>
          <%= g %><br>
        <% end %>
      </td>
      <td class="text-center"><%= a.active_str %></td>
      <td class="text-center"><%= link_to "Edit", edit_domain_alias_path(@domain, a),
                      role: "button", class: "btn btn-info btn-sm" %></td>
      <td class="text-center"><%= link_to "Delete", domain_alias_path(@domain, a), method: :delete,
                      data: { confirm: 'Are you sure?' },
                      role: "button", class: "btn btn-secondary btn-sm" %></td>
      <td class="text-center"><%= l a.modified %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/aliases/new.html.erb
<div class="card card-form">
  <h4 class="card-header">New alias</h4>
  <%= render 'form' %>
</div>