config/routes.rb
Rails.application.routes.draw do
  root 'domains#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'profile' => 'profile#edit'
  patch 'profile' => 'profile#update'

  resources :admins, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_EMAIL_LIKE do
        get 'edit'
        patch '', action: 'update', as: ''
        delete '', action: 'destroy'
      end
    end
  end

  resources :domains, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
        get 'edit', action: 'edit'
        get '', action: 'show', as: ''
        patch '', action: 'update'
        delete '', action: 'destroy'
      end
    end

    constraints domain_id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
      resources :aliases, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end

      resources :mailboxes, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end
    end
  end


end

app/models/domain.rb
class Domain < ApplicationRecord
  self.table_name = :domain
  self.primary_key = :domain

  validates :domain, presence: true, uniqueness: true,
                     format: { with: RE_DOMAIN_NAME_LIKE_WITH_ANCHORS,
                               message: "must be a valid domain name" }
  validates :transport, presence: true

  validates :aliases, presence: true,
                      numericality: { only_integer: true,
                                      greater_than_or_equal_to: 0 }
  validates :mailboxes, presence: true,
                        numericality: { only_integer: true,
                                        greater_than_or_equal_to: 0 }
  validates :maxquota, presence: true,
                       numericality: { only_integer: true,
                                       greater_than_or_equal_to: 0 }

  has_many :rel_mailboxes, class_name: "Mailbox", foreign_key: :domain,
                           dependent: :destroy
  has_many :rel_aliases, class_name: "Alias", foreign_key: :domain,
                         dependent: :destroy

  before_validation do |domain|
    domain.domain = domain.domain.downcase unless domain.domain.empty?
    domain.transport = "virtual"
  end

  scope :without_all, -> { where.not(domain: "ALL") }

  def pure_aliases
    rel_aliases.pure
  end

  def aliases_unlimited?
    aliases.zero?
  end

  def mailboxes_unlimited?
    mailboxes.zero?
  end

  def aliases_str
    num_str(aliases)
  end

  def mailboxes_str
    num_str(mailboxes)
  end

  def aliases_short_str
    num_short_str(aliases)
  end

  def mailboxes_short_str
    num_short_str(mailboxes)
  end

  def maxquota_str
    if maxquota.zero?
      "Unlimited"
    else
      "#{maxquota} MB"
    end
  end

  def maxquota_short_str
    if maxquota.zero?
      "--"
    else
      "#{maxquota} MB"
    end
  end

  private

  def num_str(num)
    if num.zero?
      "Unlimited"
    else
      num.to_s
    end
  end

  def num_short_str(num)
    if num.zero?
      "--"
    else
      num.to_s
    end
  end
end

app/controllers/domains_controller.rb
class DomainsController < ApplicationController
  before_action :super_admin_check, except: [:index, :show]
  before_action :set_domain, only: [:show, :edit, :update, :destroy]

  def index
    if @current_admin.super_admin?
      @domains = Domain.without_all.all
    else
      @domains = @current_admin.rel_domains.active
    end
  end

  def new
    @domain = Domain.new
  end

  def create
    @domain = Domain.new(domain_params)

    if @domain.save
      redirect_to domain_path(@domain.domain), notice: 'Domain was successfully created.'
    else
      render action: 'new'
    end
  end

  def show
    redirect_to domain_mailboxes_path(@domain)
  end

  def edit
  end

  def update
    if @domain.update(domain_params)
      redirect_to domains_path, notice: 'Domain was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @domain.destroy
    redirect_to domains_path
  end

  private

  def set_domain
    @domain = Domain.find(params[:id])
    raise "Invalid domain access" unless @current_admin.has_domain?(@domain)
  end

  def domain_params
    params.require(:domain).permit(:domain, :description, :maxquota, :aliases,
                                   :mailboxes, :active)
  end
end

app/helpers/domains_helper.rb
module DomainsHelper
end

app/views/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <div class="card-body">
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this domain from being saved:</h2>

      <ul>
        <% @domain.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :domain %><br>
    <% if controller.action_name == "edit" %>
      <%= f.hidden_field :domain, size: 50 %>
      <%= @domain.domain %>
    <% else %>
      <%= f.text_field :domain, size: 50, class: "form-control" %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, size: 50, class: "form-control" %>
  </div>

  <div class="form-group number">
    <%= f.label :aliases %><br>
    <%= f.text_field :aliases, size: 50, class: "form-control" %>
  </div>

  <div class="form-group number">
    <%= f.label :mailboxes %><br>
    <%= f.text_field :mailboxes, size: 50, class: "form-control" %>
  </div>

  <div class="form-group number">
    <%= f.label :maxquota %><br>
    <%= f.text_field :maxquota, size: 50, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= f.check_box :active, class: "form-check-input" %>
    <%= f.label :active, class: "form-check-label" %>
  </div>
  </div>

  <div class="card-footer">
    <%= f.submit(class: "btn btn-primary") %>
    <%= link_to "Cancel", domains_path, role: "button",
                          class: "btn btn-secondary" %>
  </div>

<% end %>

app/views/domains/_info.html.erb
<h1><%= @domain.domain %></h1>

<div class="mb-3 clearfix">
  <ul class="list-group list-group-horizontal float-left">
    <li class="list-group-item">
      <%= link_to "Mailboxes", domain_mailboxes_path(@domain),
                  style: "text-decoration: underline" %>
      <%= @domain.rel_mailboxes.count %> / <%= @domain.mailboxes_str %>
    </li>
    <li class="list-group-item">
      <%= link_to "Aliases", domain_aliases_path(@domain),
                  style: "text-decoration: underline" %>
      <%= @domain.pure_aliases.count %> / <%= @domain.aliases_str %>
    </li>
    <li class="list-group-item">
      <span class="font-weight-bold">Max Quota</span>
      <%= @domain.maxquota_str %>
    </li>
    <% active_class = @domain.active? ? "list-group-item-success" : "list-group-item-secondary" %>
    <li class="list-group-item <%= active_class %>">
      <span class="font-weight-bold">Status</span>
      <%= @domain.active_str %>
    </li>
  </ul>

  <div class=" float-left pt-1 ml-3">
    <%= link_to "New mailbox", new_domain_mailbox_path(@domain),
                role: "button", class: "btn btn-outline-success mx-2" %>
    <%= link_to "New alias", new_domain_alias_path(@domain),
                role: "button", class: "btn btn-outline-success mx-2" %>
  </div>
</div>

<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert"><%= notice %></div>
<% end %>

app/views/domains/edit.html.erb
<div class="card card-form">
  <h4 class="card-header">Edit domain</h4>
  <%= render 'form' %>
</div>

app/views/domains/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert"><%= notice %></div>
<% end %>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th class="text-center">#</th>
    <th>Domain</th>
    <th>Description</th>
    <th class="text-center">Mailboxes</th>
    <th class="text-center">Aliases</th>
    <th class="text-center">Max Quota</th>
    <th class="text-center">Status</th>
    <th class="text-center">Show</th>
    <% if @current_admin.super_admin? %>
      <th class="text-center">Edit</th>
      <th class="text-center">Delete</th>
    <% end %>
    <th class="text-center">Modified</th>
  </tr>
  </thead>
  <tbody>
  <% @domains.each_with_index do |domain, i| %>
    <% tr_class = domain.active? ? "" : "table-secondary" %>
    <tr class="<%= tr_class %>">
      <td class="text-center"><%= i+1 %></td>
      <td><%= domain.domain %></td>
      <td><%= domain.description %></td>
      <td class="text-center">
        <% if domain.mailboxes_unlimited? %>
          <%= domain.rel_mailboxes.count %>
        <% else %>
          <%= domain.rel_mailboxes.count %> / <%= domain.mailboxes_short_str %>
        <% end %>
      </td>
      <td class="text-center">
        <% if domain.aliases_unlimited? %>
          <%= domain.pure_aliases.count %>
        <% else %>
          <%= domain.pure_aliases.count %> / <%= domain.aliases_short_str %>
        <% end %>
      </td>
      <td class="text-center"><%= domain.maxquota_short_str %></td>
      <td class="text-center"><%= domain.active_str %></td>
      <td><%= link_to "Show", domain,
                      role: "button", class: "btn btn-primary btn-sm" %></td>

      <% if @current_admin.super_admin? %>
        <td><%= link_to "Edit", edit_domain_path(domain),
                        role: "button", class: "btn btn-info btn-sm" %></td>
        <td><%= link_to "Delete", domain, method: :delete,
                        data: { confirm: 'Are you sure?' },
                        role: "button", class: "btn btn-secondary btn-sm" %></td>
      <% end %>
      <td class="text-center"><%= l domain.modified %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/domains/new.html.erb
<div class="card card-form">
  <h4 class="card-header">New domain</h4>
  <%= render 'form' %>
</div>