config/routes.rb
Rails.application.routes.draw do
  root 'domains#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'profile' => 'profile#edit'
  patch 'profile' => 'profile#update'

  resources :admins, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_EMAIL_LIKE do
        get 'edit'
        patch '', action: 'update', as: ''
        delete '', action: 'destroy'
      end
    end
  end

  resources :domains, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
        get 'edit', action: 'edit'
        get '', action: 'show', as: ''
        patch '', action: 'update'
        delete '', action: 'destroy'
      end
    end

    constraints domain_id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
      resources :aliases, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end

      resources :mailboxes, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end
    end
  end


end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  self.table_name = :mailbox
  self.primary_key = :username

  include DovecotCramMD5Password

  attribute :quota_mb, :integer

  validates :username, presence: true, uniqueness: true,
                       format: { with: RE_EMAIL_LIKE_WITH_ANCHORS,
                                 message: "must be a valid email address" }
  validates :maildir, presence: true, uniqueness: true
  validates :local_part, presence: true
  validates :quota, presence: true,
                    numericality: { only_integer: true,
                                    greater_than_or_equal_to: 0 }
  validates :quota_mb, presence: true,
                       numericality: { only_integer: true,
                                       greater_than_or_equal_to: 0 }

  belongs_to :rel_domain, class_name: "Domain", foreign_key: :domain
  has_one :alias, foreign_key: :address, dependent: :destroy
  has_one :quota_usage, class_name: "Quota", foreign_key: :username,
          dependent: :destroy

  validate on: :create do |mailbox|
    domain = mailbox.rel_domain
    if !domain.mailboxes.zero? && domain.rel_mailboxes.count >= domain.mailboxes
      message = "already has the maximum number of mailboxes " \
                "(maximum is #{domain.mailboxes} mailboxes)"
      mailbox.errors.add(:domain, message)
    end
  end

  # just in case
  validate on: :update do |mailbox|
    mailbox.errors.add(:username, 'cannot be changed') if mailbox.username_changed?
    mailbox.errors.add(:local_part, 'cannot be changed') if mailbox.local_part_changed?
  end

  validate do |mailbox|
    domain = mailbox.rel_domain
    unless domain.maxquota.zero?
      if mailbox.quota_mb.zero?
        mailbox.errors.add(:quota_mb, "cannot be 0")
      elsif mailbox.quota_mb > domain.maxquota
        message = "must be less than or equal to #{domain.maxquota} (MB)"
        mailbox.errors.add(:quota_mb, message)
      end
    end
  end

  before_validation do |mailbox|
    mailbox.name = "" if mailbox.name.nil?
    mailbox.quota = if mailbox.quota_mb.nil?
                      nil
                    else
                      mailbox.quota_mb * 1_024_000
                    end
    mailbox.username = "#{mailbox.local_part}@#{mailbox.domain}"
    mailbox.maildir = "#{mailbox.domain}/#{mailbox.username}/"
    mailbox.build_alias(local_part: mailbox.local_part, goto: mailbox.username,
                        domain: mailbox.domain)
  end

  def quota_usage_str
    if quota_usage
      usage_mb = quota_usage.bytes / 1_024_000
      usage_mb.to_s
    else
      "0"
    end
  end

  def quota_str
    if quota.zero?
      "--"
    else
      quota_mb = quota / 1_024_000
      "#{quota_mb} MB"
    end
  end
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :set_mailbox, only: [:edit, :update, :destroy]
  before_action :set_active_domain, only: [:index, :new, :create]

  def new
    @mailbox = Mailbox.new
    @mailbox.quota_mb = if @domain.maxquota.zero?
                          0
                        else
                          @domain.maxquota
                        end
  end

  def create
    @mailbox = Mailbox.new(mailbox_params)
    @mailbox.rel_domain = @domain

    # transation for InnoDB
    Mailbox.transaction do
      @mailbox.save!
    end

    redirect_to domain_path(@mailbox.domain), notice: 'Mailbox was successfully created.'

  rescue ActiveRecord::ActiveRecordError => e
    logger.error("#{e.class}: #{e}")
    flash[:notice] = "Failed to save Mailbox"
    render action: 'new'
  end

  def edit
    unless @mailbox.quota.nil?
      @mailbox.quota_mb = (@mailbox.quota / 1_024_000).to_i
    end
  end

  def update
    if @mailbox.update(mailbox_params)
      redirect_to domain_path(@mailbox.domain), notice: 'Mailbox was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @mailbox.destroy
    redirect_to domain_path(@mailbox.domain)
  end

  private

  def set_mailbox
    @mailbox = Mailbox.find(params[:id])
    set_active_domain
    raise "Invalid Paramters" if @mailbox.rel_domain != @domain
  end

  def mailbox_params
    params.require(:mailbox).permit(:local_part, :name, :password_unencrypted,
                                    :password_unencrypted_confirmation,
                                    :quota_mb, :active)
  end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<% if flash[:notice] %>
  <div class="alert alert-primary" role="alert"><%= notice %></div>
<% end %>


<%= form_for([@domain, @mailbox]) do |f| %>
  <div class="card-body">
  <% if @mailbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mailbox.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
        <% @mailbox.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :local_part %><br>
    <% if controller.action_name == "edit" %>
      <%= f.hidden_field :local_part, size: 20 %>
      <%= @mailbox.username %>
    <% else %>
      <div class="input-group">
        <%= f.text_field :local_part, size: 20, class: "form-control" %>
        <div class="input-group-append">
          <div class="input-group-text">@<%= @domain.domain %></div>
        </div>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 50, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_unencrypted %><br>
    <%= f.password_field :password_unencrypted, size: 50,
                         class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :password_unencrypted_confirmation %><br>
    <%= f.password_field :password_unencrypted_confirmation, size: 50,
                         class: "form-control" %>
  </div>

  <div class="form-group number">
    <%= f.label :quota_mb %><br>
    <%= f.text_field :quota_mb, size: 50, class: "form-control" %>
  </div>

  <div class="form-group form-check">
    <%= f.check_box :active, class: "form-check-input" %>
    <%= f.label :active, class: "form-check-label" %>
  </div>
  </div>

  <div class="card-footer">
    <%= f.submit(class: "btn btn-primary") %>
    <%= link_to "Cancel", domain_mailboxes_path(@domain), role: "button",
                          class: "btn btn-secondary" %>
  </div>

<% end %>

app/views/mailboxes/edit.html.erb
<div class="card card-form">
  <h4 class="card-header">Edit mailbox</h4>
  <%= render 'form' %>
</div>

app/views/mailboxes/index.html.erb
<%= render "domains/info" %>

<table class="table">
  <thead class="thead-dark">
  <tr>
    <th class="text-center">#</th>
    <th>Mailbox</th>
    <th>To</th>
    <th>Name</th>
    <th class="text-center">Quota</th>
    <th class="text-center">Status</th>
    <th class="text-center">Alias</th>
    <th class="text-center">Edit</th>
    <th class="text-center">Delete</th>
    <th class="text-center">Modified</th>
  </tr>
  </thead>
  <tbody>
  <% @domain.rel_mailboxes.includes(:alias).each_with_index do |m, i| %>
    <% tr_class = m.active? ? "" : "table-secondary" %>
    <tr class="<%= tr_class %>">
      <td class="text-center"><%= i+1 %></td>
      <td><%= m.username %></td>
      <td>
        <% m.alias.gotos.each do |g| %>
          <%= g %><br>
        <% end %>
      </td>
      <td><%= m.name %></td>
      <td class="text-center"><%= m.quota_usage_str %>/<%= m.quota_str %></td>
      <td class="text-center"><%= m.active_str %></td>
      <td class="text-center"><%= link_to "alias", edit_domain_alias_path(@domain, m.alias),
                      role: "button", class: "btn btn-info btn-sm" %></td>
      <td class="text-center"><%= link_to "Edit", edit_domain_mailbox_path(@domain, m),
                      role: "button", class: "btn btn-info btn-sm" %></td>
      <td class="text-center"><%= link_to "Delete", domain_mailbox_path(@domain, m), method: :delete,
                      data: { confirm: 'Are you sure?' },
                      role: "button", class: "btn btn-secondary btn-sm" %></td>
      <td class="text-center"><%= l m.modified %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/mailboxes/new.html.erb
<div class="card card-form">
  <h4 class="card-header">New mailbox</h4>
  <%= render 'form' %>
</div>