config/routes.rb
Rails.application.routes.draw do
  root 'domains#index'
  get    'login'  => 'sessions#new'
  post   'login'  => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'profile' => 'profile#edit'
  patch 'profile' => 'profile#update'

  resources :admins, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_EMAIL_LIKE do
        get 'edit'
        patch '', action: 'update', as: ''
        delete '', action: 'destroy'
      end
    end
  end

  resources :domains, only: [:index, :new, :create] do
    member do
      constraints id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
        get 'edit', action: 'edit'
        get '', action: 'show', as: ''
        patch '', action: 'update'
        delete '', action: 'destroy'
      end
    end

    constraints domain_id: ApplicationRecord::RE_DOMAIN_NAME_LIKE do
      resources :aliases, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end

      resources :mailboxes, only: [:index, :new, :create] do
        member do
          constraints id: ApplicationRecord::RE_EMAIL_LIKE do
            get 'edit', action: 'edit'
            patch '', action: 'update', as: ''
            delete '', action: 'destroy'
          end
        end
      end
    end
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container" style="margin-bottom: 30px">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="margin-bottom: 20px">
      <%= link_to "MailAdmin", root_path, class: "navbar-brand" %>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% admins_class = controller.controller_name == "admins" ? "active" : ""  %>
          <% domains_class = controller.controller_name == "domains" ? "active" : ""  %>
          <% if @current_admin.super_admin? %>
          <li class="nav-item <%= admins_class %>">
            <%= link_to "Admins", admins_path, class: "nav-link",
                        style: "text-decoration: underline" %>
          </li>
          <% end %>
          <li class="nav-item <%= domains_class %>">
            <%= link_to "Domains", domains_path, class: "nav-link",
                        style: "text-decoration: underline" %>
          </li>
        </ul>

        <% if @current_admin.super_admin? %>
          <%= link_to "New admin", new_admin_path,
                      role: "button", class: "btn btn-outline-success",
                      style: "margin: 0 8px" %>

          <%= link_to "New domain", new_domain_path,
                      role: "button", class: "btn btn-outline-success",
                      style: "margin: 0 8px" %>
        <% end %>

        <div class="dropdown ml-md-auto">
          <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class=""><%= @current_admin.username %></span>
          </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <%= link_to "Profile", profile_path, class: "dropdown-item" %>
            <%= link_to "Sign out", logout_path, method: :delete,
                        role: "button", class: "dropdown-item" %>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailadmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="text-align: center;">
  <div class="container">
    <h1 style="margin-top: 50px">Mailadmin</h1>
    <%= yield %>
  </div>
  </body>
</html>